spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/github.ae/github.ae.yaml
namespace: ApiClients\Client\GitHubAE
destination:
  root: ../
  source: clients
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
subSplit:
  templatesDir: ../templates
  branch: v0.2.x
  subSplitConfiguration: etc/config.subsplit-publish.json
  fullName: GitHub AE {{ section }}
  vendor: api-clients
  sectionGenerator:
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\OperationIdSlash
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\WebHooks
  rootPackage:
    name: github-ae
    repository: git@github.com:php-api-clients/github.git
  sectionPackage:
    name: github-ae-{{ section }}
    repository: git@github.com:php-api-clients/github-{{ section }}.git
